name: Theorie 
description: Music Theory Learning and Exploration

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_stripe: ^11.5.0
  provider: ^6.1.5
  http: ^1.1.0
  
  # Core Firebase packages
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  cloud_functions: ^5.6.0  # NEW: Firebase Cloud Functions
  
  # Web-specific Firebase implementations (automatically included when targeting web)
  firebase_core_web: ^2.24.0
  firebase_auth_web: ^5.15.1
  cloud_firestore_web: ^4.4.3
  
  # Local Storage and Utilities
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  
  # UI Components
  flutter_markdown: ^0.7.7+1
  
  # Core utilities
  meta: ^1.15.0
  
  # Audio System - NEW
  flutter_midi_command: ^0.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true